[package]
name = "module_2"
edition = "2024"

# implicit-dependencies = false
[dependencies]
# sui = {git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework/", rev= "main"}
# haha = {git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework/", rev= "main", rename-from = "sui"}


